name: Trivy File System Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.39.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.39.0_Linux-64bit.deb
          rm trivy_0.39.0_Linux-64bit.deb

      - name: Run Trivy on Local File System
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL --ignore-unfixed .
